### ISSUE TITLE
Add debug logging of arguments

### ISSUE THREAD

**Issue by dkozel** [sockeqwe/fragmentargs#27]
I use [hugo](https://github.com/JakeWharton/hugo) as an aid in debugging during development. It would be very useful if fragments annotated with `@DebugLog` would print out the values of the arguments passed in.

If you don't want to overload the annotation then perhaps `@DebugArgs`?

**Comment by sockeqwe** [comment]
I don't think it makes sense to provide a own logging implementation (i.e. triggered by `@DebugArgs`).

I think a third party logging integration like hugo could be added to fragmentargs.
What exactly do you want to log? The constructor of the builder and the optional fields? i.e. I could simply annotate the generated FragmentBuilder with `@DebugLog`:
```java
public class MyFragmentBuilder{

   @DebugLog
   public MyFragmentBuilder(String arg1, int arg2) { ... }

   @DebugLog
   public MyFragmentBuilder(String optionalArg1) { ... }

```

What do you think?

**Comment by dkozel** [comment]
Could you "inherit" the annotation? If MyFragment is annotated with `@DebugLog` then annotate the builder methods with `@DebugLog`? That way it's easy to enable/disable the logging.

**Comment by sockeqwe** [comment]
yep, that is what I was thinking of. 
Just annotated your Fragment class with `@DebugLog` like this:

```java
@DebugLog
class MyFragment extends Fragment { ... }
```

which will generate the builder annotated with `@DebugLog`:
```java
@DebugLog
public class MyFragmentBuilder{

   public MyFragmentBuilder(String arg1, int arg2) { ... }

   public MyFragmentBuilder(String optionalArg1) { ... }

}
```

**Comment by dkozel** [comment]
That would be really great and supply precisely the useful functionality.

**Comment by sockeqwe** [comment]
Maybe I will introduce a FragmentArgs specific Log annotation like `@DebugArgs` to annotate Fragments just to be a little bit more independent from hugo. Who knows how things will develop in future.

```java
@DebugArgs
class MyFragment extends Fragment { ... }
```
which will generate the builder annotated with hugo's `@DebugLog`:

```java
@DebugLog
public class MyFragmentBuilder{

   public MyFragmentBuilder(String arg1, int arg2) { ... }

   public MyFragmentBuilder(String optionalArg1) { ... }

}
```

By introducing an own `@DebugArgs` Annotation we could swap things one day, like logging with another library instead of hugo, but the user of FragmentArgs does not have touch his project source code.

I will try time to implement that at the end of August.

**Comment by dkozel** [comment]
Thanks! I look forward to using it.
