### ISSUE TITLE
diff btw this lib and SalomonBrys/Android-FragmentArgumentProcessor

### ISSUE THREAD

**Issue by sirvon** [sockeqwe/fragmentargs#29]
can you tell me whats the diff btw this lib and this similar but older lib:

https://github.com/SalomonBrys/Android-FragmentArgumentProcessor

thanks

**Comment by sockeqwe** [comment]
I just can compare the readme files, which btw. could have been done by you as well.

The main difference seems to be the way you have to declare the Arguments for a fragment: In my library you do that by annotating a field of a fragment class, the other library ask you to define arguments incl. name and types for generating a extra class to read the arguments from.

I cant say more about other features like optional arguments, inheritance, support for not parcelable datastructure etc. because there are no such things mentioned in the readme.

Why don't you just play around with both libraries and pick that one you like the most / fits your needs

instead of asking this things on github? https://github.com/SalomonBrys/Android-FragmentArgumentProcessor/issues/1

**Comment by john156** [comment]
:+1:

**Comment by sirvon** [comment]
thanks for the reply....too busy playing around with your other fascinating libs!....time its all about time.
