### ISSUE TITLE
Should be builder automatically removed?

### ISSUE THREAD

**Issue by Kikju** [sockeqwe/fragmentargs#36]
Hi, this is great library and save me lot of time.
But I think, that I found a bug.
If I create some fragment with arguments, after gradle refreshing it will be generated builder to this fragment. But when I completely remove  `@FragmentWithArgs` and also all `@Arg` anotations builder stays in generated folder.

**Comment by sockeqwe** [comment]
This is not a bug of this library. This is an [android-apt](https://bitbucket.org/hvisser/android-apt) plugin thing. However, I wouldn't call it an issue. If I do a `Project -> rebuild` or `Project -> clean` Builder are regenerated (and old removed). Perhaps that it doesn't clean the generated builders if you simply press the green play button to start your app, but this might be by design. I would recommend you to ask this question on  [android-apt](https://bitbucket.org/hvisser/android-apt) site.

As already said, this is not an issue of this library and from my point of view this is not an issue at all.
