### ISSUE TITLE
NullPointerException when using fragment without the builder

### ISSUE THREAD

**Issue by zhoul-HS** [sockeqwe/fragmentargs#44]
Hi,
I have a fragment with only optional arguments.
There are times when I don't need to sent any of them, so I just create the fragment normally with `new MyFragment()` in which case `getArguments()` return null, and the generated code tries to call getArguments().getBoolean("arg") in injectArguments:

``` java
  public static final void injectArguments(@NonNull MyFragment fragment) {
    Bundle args = fragment.getArguments();

// args == null. NPE. should probably add args != null &&
    if (args.getBoolean("com.hannesdorfmann.fragmentargs.custom.bundler.2312A478rand.ARG_DATA")) {
      fragment.mData = bundler1.get("ARG_DATA", args);
    }
  }
```

This basically prevents using it without the builder in certain cases. which doesn't sound good to me.

**Comment by sockeqwe** [comment]
Thanks for reporting. I thought this has already been fixed #30 

Are you using the latest version of FragmentArgs?

**Comment by zhoul-HS** [comment]
It seems in the fix the non-null check is only if we have at least 1 required argument, while I only have optional.
Why would you check only if required?

**Comment by sockeqwe** [comment]
Now I see the problem.

I think it's considered bad practice to instantiate a fragment without the builder (even if there is no argument you have to pass in). The reason is that, if one day this fragment will have an argument your code still compiles but will crash at runtime (because the argument has not been set). So you have to track down where you construct your Fragment manually and change that part. Whereas, if you would use FragmentArgsBuilder from the very beginning, after having added an argument to your fragment, your code will not compile anymore, because of the Builder (will have syntax errors).

Nevertheless, you are right that there should be an error, i.e. an exception that the Fragment wasn't setup with FragmentArgs.

**Comment by zhoul-HS** [comment]
hmm the situation you described is exactly what happens if I use the fragment normally (new MyFrag). I get an exception. Furthermore, it makes knowing the FragmentArgs way of instantiating mandatory.
If I need to change arguments, runtime exception are inevitable, especially with optional arguments.

**Comment by sockeqwe** [comment]
Ok, lets compare and imagine I would simply fix this null pointer exception you are facing:

1. Let's say you have the following Fragment with one required argument and we forget to set the argument:

```java 
@FragmentWithArgs
class MyFragment extends Fragment { 
    @Arg String foo;
} 
```
- `new MyFragment()` --> runtime exception when accessing foo 
- `new MyFragmentBuilder()` --> compile time error since argument is missing

2. With an optional argument:
```java 
@FragmentWithArgs
class MyFragment extends Fragment { 
    @Arg(requrired = false) String optional;
} 
```
- `new MyFragment()` --> runtime exception when accessing 
- `new MyFragmentBuilder()` --> runtime exception when accessing

So you are right, optional arguments can always lead to runtime exception,**but** since the argument is optional you as programmer are always responsible to deal with optional values.

3. An zero argument Fragment class:
```java 
@FragmentWithArgs
class MyFragment extends Fragment { 
} 
```
Will compile with both.
but what if you add an argument oneday?

- `new MyFragment()` --> runtime exception when accessing 
- `new MyFragmentBuilder()` --> compiletime exception

4. In general it should be not possible to instantiate a Fragment without Builder, because if you have a class like 
```java 
@FragmentWithArgs
class MyFragment extends Fragment { 
    @Arg String foo;
} 
```
and instantiate it manually with `new MyFragment()` then the whole "contract" that the fragment has arguments set will no longer hold.

```java 
@FragmentWithArgs
class MyFragment extends Fragment { 
    @Arg String foo;

   void onCreate(Bundle b){
       FragmentArgs.inject(this); // should throw an exception that the argument wasn't instantiated via builder
   }
} 
```
 Therefore,  the code shown above should throw an exception at ` FragmentArgs.inject(this);` since we can't guarantee that the arguments "contract" holds when instantiating the Fragment manually with `new MyFragment()` .
