### ISSUE TITLE
Warning when implementing ArgsBundler

### ISSUE THREAD

**Issue by Tagakov** [sockeqwe/fragmentargs#53]
When I am copying implementation of any ArgsBundler from sources, for example NoneArgsBundler, Android Studio warns me about unchecked method overriding. Is it a bug or my misunderstanding? What is the reason of using this generic in interface: <V extends T> ? Why we should can't use T generic type instead?

**Comment by sockeqwe** [comment]
What exactly do you mean? `NoneArgsBundler` is for internal purpose only (to tell FragmentArgs that no custom ArgsBundler should be used). `ParcelerArgsBundler` per se is not "checked" therefore this warning will be displayed. 

This warning should be supressed by the library.

Regarding the type `<T>`. The readme had an error that might was misleading. I have changed that.

For instance to write a custom ArgsBundler for types of Date you have to implement something like this:

```java
public class DateArgsBundler implements ArgsBundler<Date>{

    @Override public void put(String key, Date value, Bundle bundle) {
        
        bundle.putLong(key, value.getTime());
    }

    @Override public Date get(String key, Bundle bundle) {
        
        long timestamp = bundle.getLong(key);
        return new Date(timestamp);
    }

}

public class MyFragment extends Fragment {

    @Arg ( bundler = DateArgsBundler.class )
    Date date;

}
```

**Comment by Tagakov** [comment]
The way how to implement custom ArgsBundler is clear. I just want to pointed out that when using Android Studio auto generating for interface implementation we will have :
```Java
public class DateArgsBundler implements ArgsBundler<Date> {

    @Override
    public void put(String key, Date value, Bundle bundle) {

    }

    @Override
    public <V extends T> V get(String key, Bundle bundle) {
        return null;
    }

}
```

Which is obviously incorrect. When we fix method get like this
```Java

    @Override
    public Date get(String key, Bundle bundle) {
        return null;
    }
```

We will have Unchecked overriding warning. This happens because the return type of get method in parametrized interface `ArgsBundler<T>` is `<V extends T> V`.

Maybe this is reasonable approach, but I cant understand the reason. Can you please explain it?

**Comment by sockeqwe** [comment]
Ah, now I understand what you mean.

The reason was [Parceler](https://github.com/johncarl81/parceler) and other libraries that are working in a similar fashion.

But lets stick with Parceler. The problem with parceler is that the api `Parcels.wrap()` and `Parcels.unwrap()` are defined as follows:

```java
public static <T> T unwrap(Parcelable input);
```

The problem is that those methods from Parceler have generic type methods parameters and that java generics are not strong enough to detect a safe cast somehow:
```java
fragment.foo = fooBunder.get(key, bundle);
```

Where foo is some class `Foo` annotated with `@Parcel`. Java can't resolve that type correctly otherwise, so ` <V extends T> fooBundler.get()` requires method arguments too. 

If you know a better way, don't hesitate to prove me wrong an I will change that
