### ISSUE TITLE
Warning _varname_ will be stored as Serializable

### ISSUE THREAD

**Issue by IlyaEremin** [sockeqwe/fragmentargs#8]
Hi.
First of all: great thanks for library!
When I pass objects which implements Serializable interface via Arg annotation I get following message during _compileDebugJava (I use Android Studio 1.0):
```
Warning: _varibale_ type will be stored as Serializable
```
My code:
```
public class SomeFragment {
    @Arg Status status;
    // ...
}

public class Status implements Serializable {
    // class inners
}

public class MainClass {
    public void func(){
        replaceFragment(new SomeFragmentBuilder(status).build());
    }
}
```
How can I rid off this message in a "legal" way and have no deals with casting serializable objects back and forth?

**Comment by sockeqwe** [comment]
Hi, this warning indicates that your `@Arg` annotated field will be stored as `Serializeable`. Usually you would prefer `Parcelable` over `Serializeable` on android because Parcelable offers a much better performance. However, if it's just a simple object  with not many fields etc. you can go on with `Serializeable`.

> How can I rid off this message in a "legal" way and have no deals with casting serializable objects back and forth?
Simply make `Status` implement `Parcelable`. Btw. I 've written an annotation processor for generating Parcelable called [ParcelablePlease](https://github.com/sockeqwe/ParcelablePlease)

FragmentArgs supports java primitives (like int, string, float), Parcelable (including ArrayList and Arrays of Parceables) and plain old java Serializeable as fallback.

**Comment by IlyaEremin** [comment]
Thanks for quick response!
