### ISSUE TITLE
New release that allows to obtain a bundle from builder

### ISSUE THREAD

**Issue by AndreasBoehm** [sockeqwe/fragmentargs#82]
Hello @sockeqwe,

our team really likes fragmentargs and we use it in a multiple projects already.
Recently we where looking for a way to use fragmentargs to generate a Bundle that we can use where we can not instantiate a Fragment directly.

If have seen that this functionality is available in the snapshot version since may 2016.

Is there any release planned within the next few days/weeks that will provide this feature in a non-snapshot version?

Best Regards,
Andreas

**Comment by sockeqwe** [comment]
Oh boy, I'm really sorry ... I just have focused my open source time on other project as they have had higher priority for me since we use FragmentArgs version 3 at work and it fits our needs.

There are still some tasks / issues open for a stable  4.0 version: https://github.com/sockeqwe/fragmentargs/milestone/4

The most important ones are #46  #44 #73 #83 #82 and #17 . The remaining ones could also be "fixed" in a minor version like `4.0.1` 

I can't give any serious estimation when I will have time to work on this, but "within few days" is not possible for me. I think first week of August is realistic.

If someone wants to contribute, pull requests are very welcome!

**Comment by AndreasBoehm** [comment]
Thanks for the quick reply!

I will try to support you getting tasks/issues fixed for version 4.0 👍
