### ISSUE TITLE
TransactionTooLargeException on Nougat

### ISSUE THREAD

**Issue by IIB3II** [sockeqwe/fragmentargs#95]
Hello @sockeqwe !
I like this lib fragmentargs and i use it in a multiple projects already!
But some time ago i have bug on Android Nougat TransactionTooLargeException with object large > 1mb.
Mb you know about this problem and you have some fix, for it?

**Comment by sockeqwe** [comment]
The data you put into a bundle, such as arguments for a fragment, is limited to around 1 MB (depends on Android version). So simply your object (or the sum of the objects) you would like to pass as argument to a Fragment is simply exceeding the limit.

This is not a FragmentArgs issue. You will see the same issue if setting arguments for a Fragment manually. Also you will see the same this issue if you put too much data in a bundle to start an Activity. 

So there is nothing FragmentArgs can do, you have to fix this issue on your side by not putting such big data as arguments of a Fragment. Instead of passing around data consider passing around an id that can be used in the fragment to load the required data.
